# Replays the battles generated by the JS prototype and writes the logs for comparison.
extends RefCounted

func run(_root) -> void:
	var cfgs = JSON.parse_string(FileAccess.open("user://../../parity_configs.json", FileAccess.READ).get_as_text()) if false else _load("/tmp/claude-0/parity/configs.json")
	var out := []
	for c in cfgs:
		c = D._ints(c)
		var b := Battle.new(c)
		var steps := 0
		while b.over == null and steps < 20000:
			CombatAI.step(b)
			steps += 1
		var lines := []
		for l in b.log:
			lines.append(l.t)
		out.append({"log": lines, "over": b.over, "round": b.round_n})
	var f := FileAccess.open("/tmp/claude-0/parity/gd.json", FileAccess.WRITE)
	f.store_string(JSON.stringify(out))
	print("parity: ran %d battles" % out.size())

func _load(p: String):
	return JSON.parse_string(FileAccess.open(p, FileAccess.READ).get_as_text())
